FROM dockerbase/cron

MAINTAINER Bill Maxwell <bill@rancher.com>

ADD . /tmp/

RUN /tmp/bootstrap
RUN pip install /tmp/dist/rldc-*.tar.gz

ADD services/cron.run /etc/service/cron/run
RUN chmod 755 /etc/service/cron/run

ADD wrap_cron /usr/local/bin/
RUN chmod 755 /usr/local/bin/wrap_cron 

ADD crontabs/nobody /var/spool/cron/crontabs/
RUN chown nobody /var/spool/cron/crontabs/nobody
RUN chmod 600 /var/spool/cron/crontabs/*

CMD [ "runit" ]
